# .github/workflows/module_upgrade_test.yaml
name: Terraform Module Upgrade Test

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - '*.tf'
      - 'tests/**/*.tf'
      - 'tests/**/*.tfvars'
      - 'VERSION'

permissions:
  contents: read
  pull-requests: write


jobs:
# -------------------------------------
# Job: Discover semantic version tags
# -------------------------------------
  discover-tags:
    name: Discover semantic version tags
    runs-on: ubuntu-latest
    env:
      INCLUDE_PREVIOUS_MAJOR_VERSION: true # set to false to skip N-1 major version test
    outputs:
      has_tags: ${{ steps.get-tags.outputs.has_tags }}
      tags: ${{ steps.get-tags.outputs.tags }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest semver tags
        id: get-tags
        shell: bash
        run: |
          set -e
          git fetch --tags
          tags=$(git tag -l 'v[0-9]*.[0-9]*.[0-9]*' | grep -Ev -- '-' || true)
          if [ -z "$tags" ]; then
            echo "No semantic version tags found. Skipping upgrade test."
            echo "tags<<EOF" >> $GITHUB_OUTPUT
            echo "[]" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            echo "has_tags=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          sorted_tags=$(echo "$tags" | sort -V)
          major_versions=$(echo "$sorted_tags" | sed -E 's/^v([0-9]+)\..*/\1/' | sort -nr | uniq)
          current_major=$(echo "$major_versions" | head -n1 || true)
          prev_major=$(echo "$major_versions" | sed -n 2p || true)
          latest_tag=""
          prev_major_tag=""
          if [ -n "$current_major" ]; then
            latest_tag=$(echo "$sorted_tags" | grep "^v${current_major}\." | tail -n1 || true)
          fi
          if [ -n "$prev_major" ]; then
            prev_major_tag=$(echo "$sorted_tags" | grep "^v${prev_major}\." | tail -n1 || true)
          fi
          arr=()
          [ -n "$latest_tag" ] && arr+=("$latest_tag")
          if [[ "${INCLUDE_PREVIOUS_MAJOR_VERSION}" == "true" ]]; then
            [ -n "$prev_major_tag" ] && arr+=("$prev_major_tag")
          fi
          arr_json=$(printf '%s\n' "${arr[@]}" | jq -R . | jq -s -c .)
          echo "has_tags=true" >> $GITHUB_OUTPUT
          echo "tags<<EOF" >> $GITHUB_OUTPUT
          echo "${arr_json}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "Discovered tags: ${arr_json}"
      
      # - name: Print discovered tags
      #   run: |
      #     echo "Discovered tags: ${{ steps.get-tags.outputs.tags }}"

# -------------------------------------
# Job: Upgrade test matrix
# -------------------------------------
  upgrade-test:
    name: 'Upgrade test from: ${{ matrix.upgrade_from }}, test_dir: ${{ matrix.test_dirs }}'
    needs: discover-tags
    if: needs.discover-tags.outputs.has_tags == 'true'
    runs-on: ubuntu-latest
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        test_dirs: [integration-test-1, integration-test-2]
        upgrade_from: ${{ fromJson(needs.discover-tags.outputs.tags) }}
        terraform_version: [1.12.2]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform_version }}

      - name: Print test details
        run: |
          echo "Testing upgrade from module version ${{ matrix.upgrade_from }}."
          echo "Testing Terraform version ${{ matrix.terraform_version }}."
      
      - name: Checkout baseline module version (upgrade_from)
        run: |
          BASELINE_DIR="baseline-${{ matrix.upgrade_from }}"
          git clone . "$BASELINE_DIR"
          cd "$BASELINE_DIR"
          git checkout "${{ matrix.upgrade_from }}"
          ls -l

      - name: Update module source to baseline version
        run: |
          BASELINE_DIR="baseline-${{ matrix.upgrade_from }}"
          sed -i 's|source = .*|source = "git::https://github.com/${{ github.repository }}.git//.?ref=${{ matrix.upgrade_from }}"|' "$BASELINE_DIR/tests/${{ matrix.test_dirs }}/main.tf"

      - name: Terraform Init + Apply baseline version
        run: |
          BASELINE_DIR="baseline-${{ matrix.upgrade_from }}"
          cat "$BASELINE_DIR/tests/${{ matrix.test_dirs }}/main.tf"
          terraform -chdir="$BASELINE_DIR/tests/${{ matrix.test_dirs }}" init -input=false
          terraform -chdir="$BASELINE_DIR/tests/${{ matrix.test_dirs }}" apply -auto-approve

      # needed for Terraform Community Edition where the statefile is local to the GitHub runner
      # - name: Copy state and .terraform to target version test dir
      #   run: |
      #     BASELINE_DIR="baseline-${{ matrix.upgrade_from }}"
      #     cp "$BASELINE_DIR/tests/${{ matrix.test_dirs }}/terraform.tfstate" tests/${{ matrix.test_dirs }}/ || true
      #     cp -r "$BASELINE_DIR/tests/${{ matrix.test_dirs }}/.terraform" tests/${{ matrix.test_dirs }}/ || true

      - name: Switch to local module source (current branch)
        run: |
          sed -i 's|source = .*|source = "../.."|' tests/${{ matrix.test_dirs }}/main.tf

      - name: Terraform Init + Plan target version
        id: plan_target_version
        run: |
          terraform -chdir=tests/${{ matrix.test_dirs }} init -upgrade -input=false
          terraform -chdir=tests/${{ matrix.test_dirs }} plan -detailed-exitcode -input=false -out=tfplan || exit_code=$?
          echo "exit_code=${exit_code:-0}" >> "$GITHUB_OUTPUT"

      - name: Save Terraform Plan Output
        run: |
          terraform -chdir=tests/${{ matrix.test_dirs }} show -no-color tfplan > plan.txt

      - name: Comment plan on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('plan.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Terraform Plan (Upgrade Test from \`${{ matrix.upgrade_from }}\`, test_dir: \`${{ matrix.test_dir }}\`)\n\`\`\`\n${plan}\n\`\`\``

            });

      - name: Terraform Apply target version
        if: steps.plan_target_version.outputs.exit_code == '2'
        run: |
          terraform -chdir=tests/${{ matrix.test_dirs }} apply -input=false tfplan

      - name: Terraform Destroy
        if: always()
        run: |
          terraform -chdir=tests/${{ matrix.test_dirs }} destroy -auto-approve